// src/lib/districtsData.ts
export const districtsMap: Record<string, string> = {
  "hoan-kiem": "Hoàn Kiếm",
  "ba-dinh": "Ba Đình",
  "dong-da": "Đống Đa",
  "cau-giay": "Cầu Giấy",
  "thanh-xuan": "Thanh Xuân",
  "hai-ba-trung": "Hai Bà Trưng",
  "quan_tay_ho": "Tây Hồ",
  "quan_long_bien": "Long Biên",
  "quan_dong_da": "Đống Đa",
  "quan_hai_ba_trung": "Hai Bà Trưng",
  "quan_hoang_mai": "Hoàng Mai",
  "quan_thanh_xuan": "Thanh Xuân",
  "huyen_soc_son": "Sóc Sơn",
  "huyen_dong_anh": "Đông Anh",
  "huyen_gia_lam": "Gia Lâm",
  "huyen_dong_my": "Đông Mỹ",
  "huyen_thanh_tri": "Thanh Trì",
  "huyen_thuong_tin": "Thường Tín",
  "huyen_phu_xuyen": "Phú Xuyên",
  "huyen_me_linh": "Mê Linh",
  "huyen_ba_vi": "Ba Vì",
  "huyen_phuc_tho": "Phúc Thọ",
  "huyen_thach_that": "Thạch Thất",
  "huyen_quoc_oai": "Quốc Oai",
  "huyen_chuong_my": "Chương Mỹ",
  "huyen_thanh_oai": "Thanh Oai",
  "huyen_my_duc": "Mỹ Đức",
  "huyen_ung_hoa": "Ứng Hòa",
  "huyen_hoai_duc": "Hoài Đức",
  "huyen_dan_phuong": "Đan Phượng",
  "huyen_thi_xa_son_tay": "Sơn Tây",
};
