const mapCodeToCodename: Record<number, string> = {
  1: "quan_ba_dinh",
  2: "quan_hoan_kiem",
  3: "quan_tay_ho",
  4: "quan_long_bien",
  5: "quan_cau_giay",
  6: "quan_dong_da",
  7: "quan_hai_ba_trung",
  8: "quan_hoang_mai",
  9: "quan_thanh_xuan",
  10: "huyen_soc_son",
  11: "huyen_dong_anh",
  12: "huyen_gia_lam",
  13: "huyen_dong_my",
  14: "huyen_thanh_tri",
  15: "huyen_thuong_tin",
  16: "huyen_phu_xuyen",
  17: "huyen_me_linh",
  18: "huyen_ba_vi",
  19: "huyen_phuc_tho",
  20: "huyen_thach_that",
  21: "huyen_quoc_oai",
  22: "huyen_chuong_my",
  23: "huyen_thanh_oai",
  24: "huyen_my_duc",
  25: "huyen_ung_hoa",
  26: "huyen_hoai_duc",
  27: "huyen_dan_phuong",
  28: "huyen_thi_xa_son_tay",
};
export default mapCodeToCodename;
